chain:
  name: Sparge
  symbol: SPRG
  chainId: "sparge-mainnet"
  blockTimeSeconds: 51
  protocolVersion: "1.0.0"
  economicsVersion: "1.0.0"

token:
  decimals: 9
  initialSupplyTokens: "5100000000"

mining:
  proposerAddress: "spg_3D9sm1pyziUMXCkqYaJML3KJRpPd"
  genesisOperatorAddress: "spg_2B4XVJv4GzPNCeP5ECCVPEB7AWX9"
  genesisFreeBlocks: 100

rewards:
  treasuryAddress: "spg_ojsJmWnCUdu8t4VWjU4CmiZkYPn"
  nodePoolAddress: "spg_PHxAiV4Tp2VwPN3QHhGt7R7JXzQ"
  holderPoolAddress: "spg_3iq23T44YH5YKu4kqdrVwb9aaE34"

storage:
  backend: sqlite
  blocksPerFile: 510

gas:
  blockLimit: 510
  targetRatioBps: 8000
  baseFeeInitialMicro: "1000"
  baseFeeChangeDenominator: 8
  minBaseFeeMicro: "0"

mempool:
  sort: fee

tx:
  minFeeMicro: "1000"

dev:
  enableAdmin: true
