const MICRO = 1_000_000n;

const ACTIVE_WINDOW_BLOCKS = 5100;
const PARTICIPANT_BOND_MICRO = 50n * MICRO;
const MAX_SPONSORED_PARTICIPANTS = 10;

module.exports = {
  ACTIVE_WINDOW_BLOCKS,
  PARTICIPANT_BOND_MICRO,
  MAX_SPONSORED_PARTICIPANTS
};
